### ISSUE TITLE
I learned ELAN at the "Theodor Heuss Gymnasium"

### ISSUE THREAD

**Issue by obestwalter** [PromyLOPh/eumel#1]
Hi and thanks for preserving this bit of computing history.

I was at the ["Theodor Heuss Gymnasium"](https://thgmedia.de/) in the 1980s and and they had a dedicated room with about 10 EUMEL machines. I learned ELAN on them and spent many happy hours with these machines. I visited my old school recently and asked the janitor if they know what happened to these machines. While not in use anymore for a long time, they were actually still there in a storage room.

**Comment by PromyLOPh** [comment]
Thank you! Do you know if any documentation or floppy disks were
preserved as well? Who was responsible for introducing EUMEL at THG?
(You can reply in private and German if you want: lars@6xq.net )
